package pe

type DllCharacteristics uint16

const (
	IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA       DllCharacteristics = 0x0020
	IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE          DllCharacteristics = 0x0040
	IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY       DllCharacteristics = 0x0080
	IMAGE_DLLCHARACTERISTICS_NX_COMPAT             DllCharacteristics = 0x0100
	IMAGE_DLLCHARACTERISTICS_NO_ISOLATION          DllCharacteristics = 0x0200
	IMAGE_DLLCHARACTERISTICS_NO_SEH                DllCharacteristics = 0x0400
	IMAGE_DLLCHARACTERISTICS_NO_BIND               DllCharacteristics = 0x0800
	IMAGE_DLLCHARACTERISTICS_APPCONTAINER          DllCharacteristics = 0x1000
	IMAGE_DLLCHARACTERISTICS_WDM_DRIVER            DllCharacteristics = 0x2000
	IMAGE_DLLCHARACTERISTICS_GUARD_CF              DllCharacteristics = 0x4000
	IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE DllCharacteristics = 0x8000
)